{{- $root := . -}}

{{- if .Values.apps -}}
  {{- range  .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-{{ $root.Values.cluster}}-{{ $root.Values.namespace.metadata.name }}-{{  .name }}
  namespace: argocd
  labels:
    level: application
spec:
  destination:
    namespace: {{ $root.Values.namespace.metadata.name }}
    name: {{ $root.Values.cluster}}
  project: cluster-infra
  source:
    path: namespaces/{{ $root.Values.namespace.metadata.name }}/{{  .name }}
    repoURL: {{$root.Values.clusterRepoURL}}
    targetRevision:  {{ .targetRevision | default (printf "main" ) }}
    {{- if .source_extra }}
    {{- .source_extra | toYaml | nindent 4}}
    {{- end }}    
  {{- if .spec_extra }} 
  {{- .spec_extra | toYaml | nindent 2}}
  {{- end }}    
---
  {{- end -}}
{{- end -}}
