{{- $root := . -}}
{{- if .Values.namespace.metadata.name }}
 
apiVersion: v1
kind: Namespace
metadata:
  {{- .Values.namespace.metadata|toYaml|nindent 2 }}
---
{{- if $root.Values.quota }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-{{ .Values.namespace.metadata.name }}
  namespace: {{.Values.namespace.metadata.name }}
spec:
  hard:
    requests.cpu: {{ $root.Values.quota.cpu | quote }}
    requests.memory: {{ $root.Values.quota.mem | quote }}
    limits.cpu: {{ $root.Values.quota.limitcpu | quote }}
    limits.memory: {{ $root.Values.quota.limitmem | quote }}
---
 
{{- end}}
{{- end}}
